### ISSUE TITLE
Don't count quoted LGTMs

### ISSUE THREAD

**Issue by tboerger** [go-gitea/lgtm#11]
You can see an example at https://github.com/go-gitea/infrastructure/pull/2#issuecomment-262787836 where the LGTM have been in a quote but it still have been counted.

**Comment by lunny** [comment]
It's really.

**Comment by cyphar** [comment]
IMO The solution is that the default regular expression should be `^LGTM`. It's what we use in runC, and it makes it very clear whether or not you LGTM (you have to start your message with it).

**Comment by tboerger** [comment]
Lgtm will die, so closing this issue.
