### ISSUE TITLE
Download site down?

### ISSUE THREAD

**Issue by PeterDaveHello** [go-gitea/lgtm#25]
The download link been mentioned in readme: http://dl.gitea.io.de/lgtm
I got this error in chrome: `ERR_NAME_NOT_RESOLVED`, nslookup can't find the result of dl.gitea.io.de

**Comment by thibaultmeyer** [comment]
The correct URL is  _dl.gitea.io_

**Comment by PeterDaveHello** [comment]
cool, but nothing there.

**Comment by lunny** [comment]
Only https://dl.gitea.io/gitea/ available now.

**Comment by appleboy** [comment]
@lunny He wanted to download `lgtm` binary.

**Comment by PeterDaveHello** [comment]
I just wonder why the link in the readme actually broken, even if the domain was corrected, there is still nothing 😅

**Comment by PeterDaveHello** [comment]
@appleboy good to see you here! Didn't notice that you are member of gitea 😄 👍

**Comment by tboerger** [comment]
@PeterDaveHello thanks for the hint, but we will close LGTM on long term because we will build a bot that implements an LGTM plugin.
