### ISSUE TITLE
Integrate GitHub approval

### ISSUE THREAD

**Issue by tboerger** [go-gitea/lgtm#3]
We should really implement the approval process of GitHub so that we are just enforcing the number of approvals.

**Comment by lunny** [comment]
In fact, we can count the lgtm on `LGTM comments + Github approvals`. Not only LGTM comments.

**Comment by tboerger** [comment]
But counting only approvals should be the safest thing, same for change requests.

**Comment by strk** [comment]
Could we then drop `LGTM` completely ?

**Comment by tboerger** [comment]
In that case we don't need lgtm comments, only approve clicks

**Comment by strk** [comment]
Sounds better to me, unless we plan to move out of github soon and thus want to have an alternative

**Comment by lunny** [comment]
count the people number who approvals and lgtms.

**Comment by lunny** [comment]
But sometimes, ad slight change, it's only lgtm what you can do. So that, I think plus the two is all right.

**Comment by strk** [comment]
keeping both is fine by me

**Comment by tboerger** [comment]
I would prefer the approval process only. Other remote drivers are anyway not implemented yet. For gitea we can do something similar when we add an approval process. Or we directly integrate that into gitea to avoid the usage of an external service for that.

**Comment by lunny** [comment]
for simple change for example a typo pr. Lgtm is the only Requirement

**Comment by tboerger** [comment]
> for simple change for example a typo pr. Lgtm is the only Requirement

I don;t understand what you mean. We should approve EVERYTHING or nothing :)

**Comment by lunny** [comment]
I mean if a PR only have changes of typo. how should we approve on github?

**Comment by tboerger** [comment]
The same way as for big changes. Instead of writing `LGTM` comments you just click the approve button of github.

**Comment by appleboy** [comment]
Already implemented in https://github.com/go-gitea/lgtm/pull/36 support both `LGTM` comments and GitHub approval.
