### ISSUE TITLE
Support for gogs/gitea

### ISSUE THREAD

**Issue by tonivj5** [go-gitea/lgtm#30]
[lgtmco/lgtm#55](https://github.com/lgtmco/lgtm/issues/55)

Thanks for maintaining this project! 😄

**Comment by Caballerog** [comment]
any news?

**Comment by lunny** [comment]
I think Gitea will integrated it internal not a separated service.

**Comment by Caballerog** [comment]
That's a great new :-)

**Comment by bkcsoft** [comment]
@lunny I would much rather see it as a separate service though. Unless we get "Approvals" integrated into CodeReview :)

**Comment by lunny** [comment]
@bkcsoft Yes, I mean that.

**Comment by lafriks** [comment]
I'm thinking on creating approval system like in GitLab but  without code review and approvals stored in database in coming weeks

**Comment by lafriks** [comment]
@bkcsoft why don't you like integrated?

**Comment by lunny** [comment]
@lafriks I like the github's approvals but I think it's need an approvals number on repository settings.

**Comment by lafriks** [comment]
Yes, that's what I'm also plan to add. When I have something to show I will create wip PR

**Comment by bkcsoft** [comment]
@lafriks External integration is fine, internal integration is not very KISS 😉

**Comment by lafriks** [comment]
Yes but internal can do a lot more and will be more reliable

**Comment by lunny** [comment]
@bkcsoft I don't think so. 
For Gitea's users, KISS means don't let me change this site to other site. Both internal or external integrations are OK.
For Gitea's manager, KISS means less maintain things(one binary/one service) since current Gitea's objective is for small teams or organizations.
Maybe it could be integrated into Gitea as well as run as a seperated service. 😄

**Comment by lafriks** [comment]
I agree with @lunny that it can be both internal or external but in both cases in gitea there should be some kind of infrastructure to store approval count/info and limit PR merging before approval conditions are met

**Comment by 6543** [comment]
gitea has it build in ...
